# German translations of the per-center descriptive content that lives in
# catalog.py's VALUE_PROPS/CENTERS (English-only). Kept in a separate module
# rather than mixed into catalog.py so the English source of truth stays
# untouched — runtime.py looks a slug up here when lang == "de" and falls
# back to the English catalog fields for anything missing (e.g. autonomously
# spawned daughter centers, which aren't in this hand-written dict).
DE_CONTENT = {
"gdpr-guard": {
 "mandate": "Ständige Zuständigkeit für Rechtsgrundlage, Datenschutzverletzungen und Betroffenenrechte über den gesamten Lebenszyklus von EU/CA-Personendaten",
 "icp": "Jede Organisation, die EU/CA-Personendaten verarbeitet",
 "value_prop": "Bevor du ein Feature launchst, das EU-Personendaten berührt: ein festes Team aus Datenschutz-, Risiko- und Datenschutzbeauftragten prüft Rechtsgrundlage und Meldepflichten — bevor es eine Behörde tut.",
 "icp_pain": "DSFAs und Consent-Checks dauern mit externer Kanzlei 6 Wochen; du brauchst die roten Flaggen in einer Stunde.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Rechtsgrundlage, Datenschutzverletzungen und Betroffenenrechten über den EU/CA-Datenlebenszyklus, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Brauchen wir eine DSFA, bevor wir unsere EU-Kundenumfrage starten?",
  "Wir speichern Support-Chats unverschlüsselt — wie viel Zeit haben wir bei einem verlorenen Laptop bis zur Meldepflicht?",
  "Unser Consent-Banner hat 'Marketing' vorangehakt — ist das rechtlich haltbar?"],
},
"ai-act-guard": {
 "mandate": "Zuständigkeit für Konformität, Risikoeinstufung und Aufsicht bei KI-Systemen auf dem EU-Markt",
 "icp": "KI-Produktteams, die in die EU ausliefern",
 "value_prop": "Ein festes Team aus KI-Governance, Sicherheit und Recht sagt dir, ob dein System unter dem EU AI Act als hochriskant gilt und welche Konformitätspflichten du hast — bevor du live gehst.",
 "icp_pain": "AI-Act-Konformität ist für die meisten Teams unklar; eine falsche Einstufung kostet bis zu 6% vom Umsatz Strafe.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Konformität, Risikoeinstufung und Aufsicht für KI-Systeme auf dem EU-Markt, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Ist unser Bewerber-Screening-Modell ein Hochrisikosystem nach Anhang III?",
  "Welche Dokumentation brauchen wir für die CE-Kennzeichnung unseres medizinischen Triage-Modells?",
  "Wir trainieren monatlich neu — löst jedes Retraining eine neue Konformitätsprüfung aus?"],
},
"sox-controls": {
 "mandate": "Zuständigkeit für interne Kontrollen und Bilanzsicherheit bei börsennotierten Unternehmen",
 "icp": "US-notierte & SOX-pflichtige Firmen",
 "value_prop": "Ein festes Team aus internen Kontrollen und Bilanzierung sagt dir, welche SOX-Prüfpunkte dein Abschlussprozess nicht belegen kann — bevor es der Wirtschaftsprüfer merkt.",
 "icp_pain": "Prüfkosten und Restatement-Risiko steigen mit Kontrolllücken, die man erst bei der Feldprüfung sieht.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei internen Kontrollen und Bilanzsicherheit für börsennotierte Unternehmen, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Welche unserer Q3-Buchungskontrollen würden bei einem Walkthrough durchfallen?",
  "Unser SOX-Umfang ist durch die Übernahme gewachsen — welche Kontrollen fehlen noch?",
  "Ist unsere Funktionstrennung wirklich durchgesetzt oder nur dokumentiert?"],
},
"hipaa-check": {
 "mandate": "Zuständigkeit für Gesundheitsdatenschutz über klinische, Kostenträger- und Zulieferer-Schnittstellen",
 "icp": "Gesundheitswesen, Versicherer, Health-Tech",
 "value_prop": "Ein festes Team aus Datenschutz, Compliance, Security und Klinik zeigt dir, wo dein Umgang mit Gesundheitsdaten eine HIPAA-Prüfung nicht bestehen würde — bevor es zu einer Datenpanne oder einem Audit kommt.",
 "icp_pain": "HIPAA-Strafen gelten pro Datensatz und können ein Health-Startup existenziell treffen.",
 "sample_question": "Wie groß ist unser aktuelles Risiko beim Schutz von Gesundheitsdaten über klinische, Kostenträger- und Zulieferer-Schnittstellen, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unsere App schickt Gesundheitsdaten an ein Analytics-SDK von Drittanbietern — ist das ein BAA-Verstoß?",
  "Müssen unsere Telemedizin-Aufnahmen nach HIPAA verschlüsselt gespeichert werden?",
  "Wir teilen anonymisierte Daten mit einem Forschungspartner — wann gelten sie noch als Gesundheitsdaten?"],
},
"contract-risk": {
 "mandate": "Zuständigkeit für Durchsetzbarkeit und Risiko von Handelsverträgen über den gesamten Einkaufs- und Verkaufsprozess",
 "icp": "Einkauf, Vertrieb, Ops-Teams",
 "value_prop": "Ein festes Team aus Vertrags-, Gesellschafts- und Einkaufsrecht prüft Durchsetzbarkeit und versteckte Risiken in deinen Verträgen — bevor du unterschreibst.",
 "icp_pain": "Eine schlechte Haftungsklausel kann die Firma beenden, und kaum jemand liest sie rechtzeitig.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Durchsetzbarkeit und Risiko von Handelsverträgen über den Einkaufs- und Verkaufsprozess, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Dieser Rahmenvertrag begrenzt unsere Haftung auf gezahlte Gebühren — ist das angesichts der IP-Freistellung durchsetzbar?",
  "Unser Dienstleistungsvertrag verlängert sich automatisch in 10 Tagen — können wir noch aussteigen?",
  "Die Reseller-Klausel erlaubt ihnen, uns zu konkurrenzieren — wie groß ist unser Risiko?"],
},
"ip-watch": {
 "mandate": "Zuständigkeit für Patentübertragung und geistiges Eigentum bei F&E und Due Diligence",
 "icp": "F&E-lastige Firmen, Startups, Pharma",
 "value_prop": "Ein festes Team aus IP-, Patent- und Gesellschaftsrecht sagt dir, wem das geistige Eigentum, das du ausliefert, wirklich gehört und wo deine Diligence-Lücken liegen.",
 "icp_pain": "Ungeprüftes IP-Eigentum lässt Übernahmen und Finanzierungsrunden über Nacht platzen.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Patentübertragung und IP-Eigentum bei F&E und Due Diligence, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unser Lead-Entwickler hat den Kernalgorithmus im vorherigen Job gebaut — wem gehört er?",
  "Wir sammeln Kapital ein — welche Patentübertragungen fehlen in unserer Diligence?",
  "Unsere Open-Source-Abhängigkeit hat eine GPL-Lizenz — infiziert das unser Closed-Source-Produkt?"],
},
"employment-law": {
 "mandate": "Zuständigkeit für Arbeitsrecht und Beschäftigungseinstufung über den gesamten Belegschafts-Lebenszyklus",
 "icp": "HR / Personalabteilung",
 "value_prop": "Ein festes Team aus Arbeitsrecht und HR erkennt Fehleinstufungen und Kündigungsrisiken — bevor die Klage kommt.",
 "icp_pain": "Fehleinstufungs- und Kündigungsschutzklagen häufen sich in Krisen und enden teuer.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Arbeitsrecht und Beschäftigungseinstufung über den Belegschafts-Lebenszyklus, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Wir stufen unsere Programmierer in 3 Bundesstaaten als Selbständige ein — ist das haltbar?",
  "Wir entlassen 12 Leute — wie sieht unsere WARN-Act-Frist aus?",
  "Unsere Wettbewerbsklausel hat den Umzug nach Kalifornien überlebt — ist sie noch durchsetzbar?"],
},
"litigation-risk": {
 "mandate": "Zuständigkeit für laufende Ansprüche und Prozessrisiko für die Rechtsabteilung",
 "icp": "Rechtsabteilung, Risikoteams",
 "value_prop": "Ein festes Team aus Prozessrecht und Ermittlungen beziffert dein Risiko bei laufenden Ansprüchen — bevor die Kanzlei dir dieselbe Einschätzung in Rechnung stellt.",
 "icp_pain": "Die Rechtsabteilung kann nicht jede Drohung bewerten; genau die ignorierte trifft am Ende.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei laufenden Ansprüchen und Prozessrisiko für die Rechtsabteilung, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Ein Kunde droht mit einer Sammelklage wegen unserer Preise — wie groß ist unser reales Risiko?",
  "Unser Ex-Vertriebler hat die Pipeline mitgenommen — haben wir einen klagbaren Geschäftsgeheimnis-Anspruch?",
  "Wir haben eine Unterlassungsaufforderung erhalten — ignorieren, vergleichen oder gegenklagen?"],
},
"license-audit": {
 "mandate": "Zuständigkeit für OSS- und Software-Lizenzkompatibilität bei ausgelieferten Produkten",
 "icp": "Engineering, OSS-nutzende Produkte",
 "value_prop": "Ein festes Team aus Lizenzrecht und Software findet den OSS-Lizenzkonflikt, der dir M&A oder den Produktbetrieb kaputt machen würde.",
 "icp_pain": "Lizenzverstöße tauchen bei der Diligence auf und können einen Deal blockieren oder verteuern.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei OSS- und Software-Lizenzkompatibilität bei ausgelieferten Produkten, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unser Produkt bündelt eine GPL-Bibliothek — muss dadurch unser ganzer Code offen werden?",
  "Wir haben ein Apache-2-Projekt geforkt und die Hinweise entfernt — wie groß ist unser Risiko?",
  "Unser SaaS nutzt eine AGPL-Abhängigkeit — reicht das bis in unseren Servercode?"],
},
"tax-exposure": {
 "mandate": "Zuständigkeit für Unternehmens- und internationales Steuerrisiko",
 "icp": "Finanz- / Steuerteams",
 "value_prop": "Ein festes Team aus Unternehmens- und internationalem Steuerrecht zeigt dir die Strukturlücken, die Prüfern und Finanzämtern zuerst auffallen.",
 "icp_pain": "Verrechnungspreis- und Betriebsstättenlücken lösen Steuernachzahlungen plus Strafen aus.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Unternehmens- und internationalem Steuerrisiko, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Wir haben IP nach Irland verlegt, aber F&E bleibt hier — sind unsere Verrechnungspreise haltbar?",
  "Unser Auftragnehmer in Deutschland ist eigentlich Angestellter — wie groß ist die Lohnsteuerlücke?",
  "Wir haben F&E-Steuergutschriften für ein gescheitertes Projekt genommen — können wir sie verteidigen?"],
},
"vendor-risk": {
 "mandate": "Zuständigkeit für Drittanbieter- und Lieferantenrisiko über das erweiterte Unternehmen",
 "icp": "Einkauf, Lieferantenmanagement",
 "value_prop": "Ein festes Team aus Drittanbieter- und Sicherheitsrisiko sagt dir, welcher Lieferant dich bei einer Lieferketten-Prüfung zu Fall bringen würde.",
 "icp_pain": "Der Datenschutzvorfall deines Lieferanten ist jetzt deiner; Behörden fragen nach beiden.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Drittanbieter- und Lieferantenrisiko über das erweiterte Unternehmen, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unser Payroll-Anbieter hat keinen SOC-2-Nachweis — ist das ein meldepflichtiges Sub-Prozessor-Risiko?",
  "Unser Cloud-Anbieter hatte gestern einen Vorfall — sind wir vertraglich abgesichert?",
  "Dieser Lieferant hat Root-Zugriff auf Kundendaten — wie kommen wir vertraglich raus?"],
},
"cyber-posture": {
 "mandate": "Zuständigkeit für Applikationssicherheit und Red/Blue-Team-Aufstellung im Engineering",
 "icp": "Security Engineering",
 "value_prop": "Ein festes Team aus AppSec, Red/Blue-Team und CISO-Perspektive findet die Lücke, die ein Angreifer nutzen würde — vor deinem nächsten Pentest oder deiner Vertragsverlängerung.",
 "icp_pain": "Versicherer verlangen jetzt Sicherheitsnachweise; ohne Nachweis keine Deckung.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Applikationssicherheit und Red/Blue-Team-Aufstellung im Engineering, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Wir haben gerade GraphQL eingeführt — welche Auth-Bypass-Fläche sehen wir nicht?",
  "Unser CI deployt mit einem geteilten Token — ist das ein Lieferketten-Risiko?",
  "Wir verlängern die Cyber-Versicherung — welche Nachweise verlangen sie?"],
},
"threat-intel": {
 "mandate": "Zuständigkeit für Bedrohungslage und SOC-Bereitschaft im Security-Betrieb",
 "icp": "SOC, CISO-Büro",
 "value_prop": "Ein festes Team aus Threat-Intel und SOC sagt dir, welche aktive Kampagne gerade auf euren Stack zielt.",
 "icp_pain": "Das Bedrohungsvolumen steigt, wenn Budgets sinken; man erfährt es erst nach dem Vorfall.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Bedrohungslage und SOC-Bereitschaft im Security-Betrieb, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Eine neue Ransomware-Gruppe trifft unsere Branche — passen wir in ihr Muster?",
  "Unsere Logs zeigen seltsame OAuth-Freigaben — ist das die MFA-Fatigue-Welle?",
  "Wir bauen Edge-Knoten aus — welches Bedrohungsmodell ignorieren wir gerade?"],
},
"incident-readiness": {
 "mandate": "Zuständigkeit für Vorfall-Reaktionsbereitschaft über SRE und Security",
 "icp": "SRE / Security-Betrieb",
 "value_prop": "Ein festes Team aus SRE und Security-Incident-Response probt deine Reaktion, damit der echte Ernstfall nicht deine erste Übung ist.",
 "icp_pain": "Behörden zählen die Meldefrist ab der ersten Kenntnis; Verwirrung kostet dich die Zeit.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Vorfall-Reaktionsbereitschaft über SRE und Security, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Wir haben unser Incident-Runbook noch nie unter Last getestet — wo bricht es?",
  "Unser Bereitschaftsdienst kann Recht nicht erreichen — ist das ein Meldepflicht-Risiko?",
  "Wir haben zwei SRE-Teams zusammengelegt — ist unser Eskalationsweg noch stimmig?"],
},
"data-governance": {
 "mandate": "Zuständigkeit für Datenkatalog, Datenqualität und Data Governance",
 "icp": "Data-Governance-Teams",
 "value_prop": "Ein festes Team aus Katalog-, Qualitäts- und Governance-Perspektive sagt dir, welche Daten du eigentlich nicht nutzen darfst — bevor ein DORA- oder DSGVO-Audit kommt.",
 "icp_pain": "Man kann nicht regieren, was man nicht sieht; Audits fangen beim Katalog an.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Datenkatalog, Datenqualität und Data Governance, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Wir trainieren Modelle mit Kundendaten ohne Herkunftsnachweis — ist das eine Rechtsgrundlage-Lücke?",
  "Unser Datenkatalog ist zu 40% veraltet — wie groß ist unsere echte PII-Fläche?",
  "Wir teilen Daten mit einem Partner — welche Rechtsgrundlage haben wir für den Auslandstransfer?"],
},
"a11y-audit": {
 "mandate": "Zuständigkeit für Barrierefreiheit (WCAG/ADA) bei Produkt- und Web-Oberflächen",
 "icp": "Produkt-, Web-Teams",
 "value_prop": "Ein festes Team aus Barrierefreiheit und Design findet den WCAG/ADA-Fehler, aus dem sonst ein Abmahnschreiben wird.",
 "icp_pain": "Auf Barrierefreiheit spezialisierte Kanzleien verschicken massenhaft Standard-Abmahnungen.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Barrierefreiheit (WCAG/ADA) bei Produkt- und Web-Oberflächen, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unser neuer Checkout ist nicht per Tastatur bedienbar — ist das ein ADA-Fall?",
  "Unsere PDFs haben keine Tags — schließen wir Screenreader-Nutzer aus?",
  "Wir sind eine öffentliche Uni-Website — an welches WCAG-Level sind wir rechtlich gebunden?"],
},
"esg-report": {
 "mandate": "Zuständigkeit für ESG-Berichterstattung und CSRD bei Nachhaltigkeit und Investor Relations",
 "icp": "Nachhaltigkeit / IR",
 "value_prop": "Ein festes Team aus ESG und IR sagt dir, welche CSRD-Angabe du nicht belegen kannst — bevor der Bericht rausgeht.",
 "icp_pain": "CSRD ist für große EU-Firmen Pflicht; unbelegte Angaben werden jetzt bestraft.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei ESG-Berichterstattung und CSRD bei Nachhaltigkeit und Investor Relations, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Wir werben mit 'klimaneutral' — ist das ein Greenwashing-Risiko?",
  "Unsere Scope-3-Daten sind zu 60% geschätzt — können wir die CSRD trotzdem unterschreiben?",
  "Unsere Diversitätskennzahlen sind nicht geprüft — wie groß ist die Nachweislücke?"],
},
"carbon-audit": {
 "mandate": "Zuständigkeit für CO2-Bilanzierung und Berichterstattung",
 "icp": "Nachhaltigkeit, Produktion",
 "value_prop": "Ein festes Team aus CO2-Bilanz und Lieferkette findet die Emissionszahl, die du unter dem Berichterstattungsgesetz verteidigen musst.",
 "icp_pain": "Emissionsberichte sind gesetzlich vorgeschrieben; überhöhte Zahlen sind ein Betrugsrisiko.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei CO2-Bilanzierung und Berichterstattung, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unser Ausgleichsportfolio besteht aus fragwürdigen Zertifikaten — hält das einer Prüfung stand?",
  "Wir berichten Scope 1-2, aber nicht 3 — unterberichten wir damit rechtlich?",
  "Unsere Lieferantendaten sind selbst gemeldet — wie groß ist unsere Nachweislücke?"],
},
"supply-chain-risk": {
 "mandate": "Zuständigkeit für Lieferkettenstörungen und Abhängigkeitsrisiko",
 "icp": "Operations, Lieferkette",
 "value_prop": "Ein festes Team aus Lieferkette und Ops findet die eine Abhängigkeit, die deine Produktion stoppen würde.",
 "icp_pain": "Störungsrisiko ist genau die Krisensituation, für die dieses Team gebaut ist.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Lieferkettenstörungen und Abhängigkeit, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unser einziger Lieferant für X sitzt in einer Sanktionszone — wie groß ist unsere Kontinuitätslücke?",
  "Wir haben zwei Lieferanten, aber beide nutzen denselben Sub-Zulieferer — sind wir wirklich diversifiziert?",
  "Ein Hafenstreik droht — wie lange reicht unser Lagerbestand?"],
},
"procure-leak": {
 "mandate": "Zuständigkeit für Einkaufs-Streuverluste und Verhandlung",
 "icp": "Einkauf, Finanzen",
 "value_prop": "Ein festes Team aus Einkauf und Finanzen findet die Streuverluste, die vor Jahresende deine Marge auffressen.",
 "icp_pain": "Kostenlecks werden in Krisen am härtesten gejagt — sie sind reine Marge.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Einkaufs-Streuverlusten und Verhandlung, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Wir verlängern SaaS-Verträge ohne Vergleichswerte — zahlen wir 30% zu viel?",
  "Unsere Bestellungen umgehen die Freigabe oberhalb einer Schwelle — wo ist das Leck?",
  "Wir haben 4 Tools für denselben Zweck — wie hoch ist die Einsparung bei Konsolidierung?"],
},
"ma-diligence": {
 "mandate": "Zuständigkeit für rechtliche und Risiko-Due-Diligence bei M&A",
 "icp": "Corporate Development, PE, VCs",
 "value_prop": "Ein festes Team aus M&A, Recht und Risiko beziffert die versteckte Haftung im Deal — bevor du die Absichtserklärung unterschreibst.",
 "icp_pain": "Die Diligence-Intensität steigt, wenn das Deal-Volumen sinkt; übersehene Punkte verteuern die Runde.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei rechtlicher und Risiko-Due-Diligence bei M&A, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Das IP des Targets wurde größtenteils von Auftragnehmern gebaut — wem gehört es wirklich?",
  "Ihre Datenschutzpraxis hatte 3 frühere Beschwerden — wie groß ist die Gewährleistungslücke?",
  "Sie nutzen einen Open-Source-Kern — gibt es eine Lizenzinfektion im Code?"],
},
"board-gov": {
 "mandate": "Zuständigkeit für Corporate Governance und Treuepflichten des Vorstands",
 "icp": "Vorstände, Governance-Teams",
 "value_prop": "Ein festes Team aus Governance und Risiko zeigt Vorständen, wo ihre Treuepflicht-Risiken wirklich liegen.",
 "icp_pain": "Governance-Versagen wird in Krisen bestraft; Vorstände haften persönlich.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Corporate Governance und Treuepflichten des Vorstands, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Wir genehmigen ein Geschäft mit nahestehenden Personen — ist der Offenlegungsweg sauber?",
  "Der Vorstand hat keine Cyber-Expertise — ist das eine Governance-Lücke?",
  "Wir schwenken mitten im Jahr um — wie groß ist das Aufsichtspflicht-Risiko?"],
},
"investor-disclosure": {
 "mandate": "Zuständigkeit für Reg-FD-/SEC-Offenlegungspflichten",
 "icp": "IR, Recht",
 "value_prop": "Ein festes Team aus IR und Recht erkennt den Offenlegungsfehler, der wesentlich wäre — bevor die Meldung raus ist.",
 "icp_pain": "Offenlegungsfehler sind immer wesentlich riskant; der Absicht ist der SEC egal.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Reg-FD-/SEC-Offenlegungspflichten, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Wir haben in einem Podcast auf den Ausblick angespielt — ist das ein Reg-FD-Verstoß?",
  "Unsere Übernahme-Meldung ist verspätet — wie groß ist das Zeitrisiko?",
  "Wir haben ein Risiko in Fußnote 14 versteckt — ist das ein Wertpapier-Anspruch?"],
},
"crisis-comms": {
 "mandate": "Zuständigkeit für Krisenkommunikation und Reputation",
 "icp": "Kommunikation, Geschäftsführung",
 "value_prop": "Ein festes Team aus Krisenkommunikation und PR formuliert die erste Reaktion — bevor die Geschichte sich selbst schreibt.",
 "icp_pain": "Kommunikationsfehler verstärken sich in Krisen — genau dann wird dieses Team am dringendsten gebraucht.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Krisenkommunikation und Reputation, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Ein Journalist hat wegen eines Lecks geschrieben — was ist unsere Halteerklärung?",
  "Unser CEO hat etwas Bedauerliches getwittert — wie dämmen wir das ein?",
  "Wir hatten einen Ausfall — was sagen wir Kunden vs. Behörden?"],
},
"insurance-review": {
 "mandate": "Zuständigkeit für Versicherungspolicen und Deckungslücken",
 "icp": "Risiko, Finanzen",
 "value_prop": "Ein festes Team aus Risiko und Finanzen findet die Deckungslücke, die den letzten Vorfall bezahlt hätte.",
 "icp_pain": "Deckungslücken tun genau dann am meisten weh, wenn man sie in Krisen braucht.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Versicherungspolicen und Deckungslücken, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unsere Cyber-Police schließt staatliche Angreifer aus — ist das unser echtes Risiko?",
  "Wir sind 3x gewachsen, aber nicht neu bewertet worden — sind wir unterversichert?",
  "Unsere D&O-Police hat eine Ausnahme bei nahestehenden Personen — höhlt das den Schutz aus?"],
},
"clinical-doc": {
 "mandate": "Zuständigkeit für klinische Studien und Pharma-Dokumentation",
 "icp": "Pharma, Auftragsforschungsinstitute",
 "value_prop": "Ein festes Team aus Klinik und Compliance findet die Kennzeichnungs- oder Dokumentationslücke, die ein Schreiben von FDA oder EMA nach sich zieht.",
 "icp_pain": "Regulierte, krisensichere Branche; Dokumentationslücken werden hart bestraft.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei klinischen Studien und Pharma-Dokumentation, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unser Einwilligungsformular für Studien ist 2 Jahre alt — ist es noch konform?",
  "Wir haben die Dosierung geändert — wurde die Prüferinformation angepasst?",
  "Unsere Werbeaussagen zitieren nur eine Studie — ist das ausreichend belegt?"],
},
"finserv-compliance": {
 "mandate": "Zuständigkeit für Fintech-Regulierung",
 "icp": "Fintech, Banken",
 "value_prop": "Ein festes Team aus Fintech und Compliance sagt dir, gegen welche Regelung du gerade verstößt — bevor die Lizenzprüfung kommt.",
 "icp_pain": "Finanzregulierung ist die beständigste Compliance-Anforderung überhaupt.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Fintech-Regulierung, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Wir fügen unserer App Krypto hinzu — wie groß ist die Lücke bei Geldtransmission?",
  "Unser KYC ist risikobasiert, aber dünn — würde es eine Prüfung überstehen?",
  "Wir bedienen EU und USA — welches Regelwerk hat die strengere AML-Regel?"],
},
"saas-security": {
 "mandate": "Zuständigkeit für SaaS-Sicherheit und Cloud-Aufstellung",
 "icp": "SaaS-Engineering, Security",
 "value_prop": "Ein festes Team aus Cloud-Sicherheit und Auth findet die Fehlkonfiguration, an der ein Kunden-Security-Review scheitern würde.",
 "icp_pain": "Cloud-Vorfälle passieren ständig; Enterprise-Käufer verlangen Nachweise vor der Unterschrift.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei SaaS-Sicherheit und Cloud-Aufstellung, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unser S3-Bucket ist versehentlich öffentlich — was ist noch offen?",
  "Wir nutzen einen geteilten Admin-Schlüssel — ist das ein SOC-2-Finding?",
  "Unsere Mandantentrennung ist logisch, nicht physisch — besteht das ein Enterprise-Review?"],
},
"payments-compliance": {
 "mandate": "Zuständigkeit für PCI-DSS und Zahlungs-Compliance",
 "icp": "Payments, E-Commerce",
 "value_prop": "Ein festes Team aus Payments und Security findet die PCI-DSS-Lücke, die dir die Zahlungsabwicklung entziehen würde.",
 "icp_pain": "Kartendaten-Regeln sind nicht verhandelbar und werden planmäßig geprüft.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei PCI-DSS und Zahlungs-Compliance, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Wir speichern Kartennummern in unserer Datenbank — sind wir überhaupt PCI-konform?",
  "Unser Checkout tokenisiert, loggt aber Kartennummern — bricht das die Regel?",
  "Wir expandieren nach Indien — wie sieht die lokale Zahlungs-Compliance aus?"],
},
"crypto-reg": {
 "mandate": "Zuständigkeit für MiCA und Krypto-Regulierung",
 "icp": "Krypto, Börsen",
 "value_prop": "Ein festes Team aus Krypto und Compliance sagt dir, welche MiCA-Pflicht dir fehlt — bevor die Behörde anruft.",
 "icp_pain": "Kryptoregulierung ist in der EU neu verpflichtend; Unwissenheit schützt nicht.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei MiCA und Krypto-Regulierung, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Wir sind Stablecoin-Emittent — wo fehlt uns die MiCA-Zulassung?",
  "Unser Whitepaper verspricht Rendite — ist das eine Wertpapier-Einstufung?",
  "Wir listen einen Token — sind wir damit eine lizenzpflichtige Börse?"],
},
"lease-review": {
 "mandate": "Zuständigkeit für Gewerbemiete und Mieterrisiko",
 "icp": "Gewerbeimmobilien, Facility Management",
 "value_prop": "Ein festes Team aus Immobilien- und Finanzrecht findet die Mietvertragsklausel, die in einer Krise zur Haftung wird.",
 "icp_pain": "Mietverträge sind Langzeit-Verbindlichkeiten, die genau dann auftauchen, wenn Cash knapp ist.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Gewerbemiete und Mieterrisiko, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unser Mietvertrag hat eine persönliche Bürgschaft — was ist das Risiko bei Schließung?",
  "Die Mieterhöhung bei Verlängerung ist 40% — können wir laut Klausel widersprechen?",
  "Wir vermieten unter, aber der Vertrag verbietet das — wie groß ist unser Risiko?"],
},
"franchise-compliance": {
 "mandate": "Zuständigkeit für Franchisevertrags-Compliance",
 "icp": "Franchisegeber",
 "value_prop": "Ein festes Team aus Franchise- und Gesellschaftsrecht findet den FTC-Regelverstoß in deinem Vertrag — bevor der Franchisenehmer klagt.",
 "icp_pain": "Franchise-Streitigkeiten wiederholen sich unabhängig von der Konjunktur.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Franchisevertrags-Compliance, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unsere Franchisegebühr ist eigentlich eine versteckte Lizenzgebühr — ein FTC-Thema?",
  "Wir kontrollieren ihre Preise — verwischen wir damit die Unabhängigkeitsgrenze?",
  "Unser Offenlegungsdokument ist veraltet — wie sieht die Aktualisierungsfrist aus?"],
},
"nonprofit-gov": {
 "mandate": "Zuständigkeit für Non-Profit-Governance und Förder-Compliance",
 "icp": "Non-Profits, Stiftungen",
 "value_prop": "Ein festes Team aus Non-Profit- und Förderrecht findet die Compliance-Lücke, die deine Förderung aussetzen würde.",
 "icp_pain": "Förder-Compliance ist Voraussetzung für Fördergelder; Fehler setzen die Zahlung aus.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Non-Profit-Governance und Förder-Compliance, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unser Förderbericht vermischt zweckgebundene Mittel — ist das ein Compliance-Verstoß?",
  "Der Vorstand hat einen Vertrag mit einer nahestehenden Person genehmigt — ist das erlaubt?",
  "Wir haben lobbyiert, aber keine Steuererklärung eingereicht — wie groß ist das Risiko?"],
},
"export-control": {
 "mandate": "Zuständigkeit für Exportkontrolle (ITAR/EAR)",
 "icp": "Verteidigung, Dual-Use-Exporteure",
 "value_prop": "Ein festes Team aus Exportrecht und Politik findet den ITAR/EAR-Fehler, der eine Strafuntersuchung auslösen würde.",
 "icp_pain": "Handelskontrollen verschärfen sich in geopolitischen Krisen; Verstöße sind strafbar.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Exportkontrolle (ITAR/EAR), und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Wir haben Dual-Use an einen Reseller geliefert, der re-exportiert — haften wir?",
  "Unsere Software hat Verschlüsselung — braucht sie eine Exportklassifizierung?",
  "Wir haben eine Person mit Exportbeschränkung im Programm eingestellt — ist das ein 'Deemed Export'?"],
},
"product-safety": {
 "mandate": "Zuständigkeit für Produktsicherheit und Haftung",
 "icp": "Hardware, Konsumgüter",
 "value_prop": "Ein festes Team aus Produkt und Qualität findet den Sicherheitsmangel, aus dem ein Rückruf wird.",
 "icp_pain": "Sicherheitsversagen wird immer beklagt; der erste Fall ist der teuerste.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Produktsicherheit und Haftung, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unser neuer Akku wird im Test heiß — ist das ein Meldeschwellenwert?",
  "Wir haben den Lieferanten gewechselt — löst das eine neue Zertifizierung aus?",
  "Ein Kind hat sich an einem Teil verschluckt — wie groß ist unser Risiko bei der Aufsichtsbehörde?"],
},
"recall-readiness": {
 "mandate": "Zuständigkeit für Rückruf- und Qualitäts-Eskalationsbereitschaft",
 "icp": "Fertigungsqualität",
 "value_prop": "Ein festes Team aus Qualität und SRE probt deinen Rückruf, damit der echte kein Feuerwehreinsatz wird.",
 "icp_pain": "Rückrufkosten sind existenzbedrohend; Bereitschaft wird schon vor der Krise verlangt.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Rückruf- und Qualitäts-Eskalationsbereitschaft, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Wir können nicht nachverfolgen, welche Charge wohin ging — sind wir rückruf-blind?",
  "Unsere Benachrichtigungsvorlage ist ungetestet — wie sieht die Behördenfrist aus?",
  "Wir haben keine Kundenkontaktdaten — wie rufen wir überhaupt zurück?"],
},
"pharma-labeling": {
 "mandate": "Zuständigkeit für Pharma-Kennzeichnung und Werbeaussagen",
 "icp": "Pharma, Medizinprodukte",
 "value_prop": "Ein festes Team aus Kennzeichnung und Compliance findet die Aussage, die eine behördliche Abmahnung nach sich zieht.",
 "icp_pain": "Kennzeichnungsfehler gehören zu den am härtesten bestraften Verstößen in der Pharmabranche.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Pharma-Kennzeichnung und Werbeaussagen, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unser Vertreter deutet eine Heilung an — ist das eine unbelegte Aussage?",
  "Wir haben die Indikation geändert, aber nicht das Etikett — wie groß ist die Lücke?",
  "Unsere Direktwerbung zitiert alte Daten — ist sie noch haltbar?"],
},
"food-safety": {
 "mandate": "Zuständigkeit für Lebensmittelsicherheits-Dokumentation",
 "icp": "Lebensmittel & Getränke",
 "value_prop": "Ein festes Team aus Lebensmittel und Qualität findet die HACCP-Lücke, aus der ein Rückruf wird.",
 "icp_pain": "Lebensmittelsicherheit ist nicht verhandelbar; ein Ausbruch kann eine Marke beenden.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Lebensmittelsicherheits-Dokumentation, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unser Lieferanten-Audit ist ein Jahr alt — ist unsere Rückverfolgbarkeit gebrochen?",
  "Wir haben einen Konservierungsstoff geändert — braucht das eine Neuvalidierung?",
  "Ein Kunde hat Glas gefunden — wie sieht unsere Rückverfolgbarkeit für diese Charge aus?"],
},
"energy-compliance": {
 "mandate": "Zuständigkeit für Energie- und NERC/EU-Compliance",
 "icp": "Versorger, Energiewirtschaft",
 "value_prop": "Ein festes Team aus Energie und NERC-Recht findet die Zuverlässigkeitslücke, die eine Strafe nach sich zieht.",
 "icp_pain": "Energieregulierung gehört zur kritischen Infrastruktur und ist entsprechend streng.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Energie- und NERC/EU-Compliance, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unsere Meldung hat das NERC-Fenster verpasst — wie groß ist das Risiko?",
  "Wir haben eine Anlage stillgelegt — haben wir die Auswirkungsmeldung eingereicht?",
  "Unser Cyber-Plan fürs Netz ist ungetestet — ist das ein Verstoß?"],
},
"telecom-compliance": {
 "mandate": "Zuständigkeit für Telekom-Regulierung",
 "icp": "Telekommunikationsanbieter",
 "value_prop": "Ein festes Team aus Telekom und Regulierung findet die Meldelücke, die deine Lizenz aussetzen würde.",
 "icp_pain": "Telekom ist eine dauerhaft regulierte kritische Dienstleistung.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Telekom-Regulierung, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unser Ausfall wurde nicht innerhalb der Frist gemeldet — wie hoch ist die Strafe?",
  "Wir haben einen neuen Dienst ohne Tarifmeldung gestartet — welches Risiko?",
  "Unser Notruf-Routing ist beeinträchtigt — ist das ein Sicherheitsverstoß?"],
},
"edu-compliance": {
 "mandate": "Zuständigkeit für Bildungsdatenschutz (FERPA)",
 "icp": "Edtech, Universitäten",
 "value_prop": "Ein festes Team aus Bildung und Datenschutz findet die FERPA-Lücke in eurem Edtech-Produkt.",
 "icp_pain": "Schülerdaten sind dauerhaft geschützt; Verstöße sind strukturell.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Bildungsdatenschutz (FERPA), und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Wir verkaufen Schülerdaten an ein Nachhilfe-Netzwerk — ist das ein FERPA-Verstoß?",
  "Unser LMS erfasst den Standort Minderjähriger — wie sieht die Einwilligungslücke aus?",
  "Wir nutzen Schülerarbeiten zum Modelltraining — wem gehört das unter FERPA?"],
},
"child-safety": {
 "mandate": "Zuständigkeit für Kinderschutz und Altersverifikation (COPPA)",
 "icp": "Consumer-Apps, Gaming",
 "value_prop": "Ein festes Team aus Kinderschutz und Altersverifikation findet die COPPA-Lücke — bevor die Behörde sie findet.",
 "icp_pain": "Kinderschutzgesetze weiten sich weltweit aus; Strafen treffen Ruf und Finanzen gleichermaßen.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Kinderschutz und Altersverifikation (COPPA), und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unter-13-Jährige in unserer App sind nicht altersgesperrt — ein COPPA-Verstoß?",
  "Wir erfassen Sprachdaten von Kindern — wie sieht die Einwilligungsfrist aus?",
  "Unser Algorithmus zeigt Minderjährigen Inhalte — was verlangt die neue Kinderschutzpflicht?"],
},
"content-policy": {
 "mandate": "Zuständigkeit für Content-Moderationsrichtlinien",
 "icp": "Social Media, UGC-Plattformen",
 "value_prop": "Ein festes Team aus Content und Richtlinien findet das Moderationsrisiko in eurer Plattform — vor der nächsten Prüfwelle.",
 "icp_pain": "Moderationshaftung steigt überall; die erste Strafe setzt den Präzedenzfall.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Content-Moderationsrichtlinien, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unser Algorithmus verstärkt schädliche Inhalte — wie groß ist unser DSA-Risiko?",
  "Wir haben kein Widerspruchsverfahren — ist das ein Verstoß gegen die neue Regel?",
  "Unsere Moderatoren sind minderjährige Auftragnehmer — wie groß ist das Risiko?"],
},
"bias-audit": {
 "mandate": "Zuständigkeit für algorithmische Verzerrung und Fairness-Audits",
 "icp": "KI/ML-Teams",
 "value_prop": "Ein festes Team aus Bias und Fairness findet die diskriminierende Wirkung in eurem Modell — bevor der Audit zur Pflicht wird.",
 "icp_pain": "Bias-Audits werden zunehmend gesetzlich verpflichtend; wer unvorbereitet ist, wird zuerst bestraft.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei algorithmischer Verzerrung und Fairness-Audits, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unser Einstellungsmodell lehnt mehr Frauen ab — ist das ein Diskriminierungsfall?",
  "Unser Kredit-Scoring hat eine Postleitzahl-Proxy — wie groß ist die Fairness-Lücke?",
  "Wir haben kein Bias-Testing — was verlangt die neue Regel?"],
},
"model-card": {
 "mandate": "Zuständigkeit für KI-Modellkarten und Dokumentation",
 "icp": "ML-Plattform-Teams",
 "value_prop": "Ein festes Team aus Modellkarten und Dokumentation baut die Nachweise, die Prüfer jetzt unter dem AI Act verlangen.",
 "icp_pain": "Dokumentationspflichten wachsen mit dem AI Act; keine Karte heißt keine CE-Kennzeichnung.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei KI-Modellkarten und Dokumentation, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unser Modell hat keine Modellkarte — was verlangt die Konformität?",
  "Wir können unsere Evaluierung nicht reproduzieren — ist die Karte haltbar?",
  "Unsere Trainingsdaten sind nicht dokumentiert — wie groß ist die Herkunftslücke?"],
},
"breach-readiness": {
 "mandate": "Zuständigkeit für Datenschutzverletzungs-Bereitschaft und Meldung",
 "icp": "Security, Recht",
 "value_prop": "Ein festes Team aus Sicherheitsvorfällen und Recht timt deine Meldung so, dass die Behörde Compliance sieht, nicht Panik.",
 "icp_pain": "Die Meldefrist bei Datenschutzverletzungen läuft rechtlich; wer sie verpasst, vervielfacht die Strafe.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Datenschutzverletzungs-Bereitschaft und Meldung, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Wir haben vor 3 Tagen einen anomalen Zugriff entdeckt — sind wir über der 72-Stunden-Frist?",
  "Wir wissen nicht, ob es 'personenbezogene Daten' sind — wie bewerten wir das?",
  "Wir haben US- und EU-Nutzer — welche Frist gilt zuerst?"],
},
"whistleblower": {
 "mandate": "Zuständigkeit für Whistleblower-Richtlinien-Compliance",
 "icp": "HR, Compliance",
 "value_prop": "Ein festes Team aus Arbeitsrecht und Compliance prüft euer Whistleblower-Programm — bevor die EU-Pflicht zuschlägt.",
 "icp_pain": "Whistleblower-Recht ist in der EU verpflichtend; Nichteinhaltung wird bestraft.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Whistleblower-Richtlinien-Compliance, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Wir haben keinen vertraulichen Meldekanal — ist das ein Verstoß gegen die EU-Whistleblower-Richtlinie?",
  "Unsere HR untersucht ihre eigenen Beschwerden — ist das ein Interessenkonflikt?",
  "Wir haben eine meldende Person benachteiligt — wie groß ist das Risiko?"],
},
"antitrust": {
 "mandate": "Zuständigkeit für Kartellrecht und Wettbewerb",
 "icp": "Corporate Development, Recht",
 "value_prop": "Ein festes Team aus Kartellrecht und Gesellschaftsrecht findet das Verhalten, das eine Razzia auslösen würde.",
 "icp_pain": "Kartellrechtliche Durchsetzung verschärft sich bei Marktkonzentration; Strafen bemessen sich am Umsatz.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei Kartellrecht und Wettbewerb, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Wir tauschen 'informell' Preise mit einem Wettbewerber aus — ein Kartellverstoß?",
  "Wir haben 70% Marktanteil — welche Pflichten als marktbeherrschendes Unternehmen haben wir?",
  "Unsere Meistbegünstigungsklausel — ist das ein vertikales Wettbewerbsproblem?"],
},
"audit-readiness": {
 "mandate": "Zuständigkeit für kontinuierliche Audit-Bereitschaft",
 "icp": "Interne Revision",
 "value_prop": "Ein festes Team aus interner Kontrolle und Audit hält euch dauerhaft bereit, damit der Audit zur Formsache wird.",
 "icp_pain": "Audits sind fortlaufend; Bereitschaft spart bei jedem Zyklus Kosten.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei kontinuierlicher Audit-Bereitschaft, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unsere Nachweise liegen in 12 Slack-Threads — ist überhaupt etwas dokumentiert?",
  "Wir können den Walkthrough vom letzten Jahr nicht reproduzieren — wo ist die Lücke?",
  "Unsere Kontrollverantwortlichen sind weg — wer trägt jetzt SOX-Verantwortung?"],
},
"resilience-review": {
 "mandate": "Zuständigkeit für operative Resilienz",
 "icp": "SRE, Ops",
 "value_prop": "Ein festes Team aus SRE und Resilienz findet den Single Point of Failure, den eure Status-Seite gerade verbirgt.",
 "icp_pain": "Resilienzbedarf ist genau in Krisen am höchsten — dann, wenn man ihn am meisten braucht.",
 "sample_question": "Wie groß ist unser aktuelles Risiko bei operativer Resilienz, und welche Fachbereiche im Team würden ihre Einschätzung am ehesten ändern, wenn wir dieses Quartal etwas Neues ausliefern?",
 "use_cases": [
  "Unser Failover wurde nie unter Last getestet — funktioniert es überhaupt?",
  "Wir haben nur eine Region — wie groß ist unser Risiko bei einem regionalen Ausfall?",
  "Unser Fehlerbudget ist aufgebraucht — was ist der Weg zum Release-Stopp?"],
},
}
